Repository oauthlib/oauthlib, pull requests merged in 2019-08, with the labels that each got.

#677 Oidc userinfo
  docs/oauth2/oidc/validator.rst
  oauthlib/oauth2/rfc6749/__init__.py
  oauthlib/openid/__init__.py
  oauthlib/openid/connect/core/endpoints/__init__.py
  oauthlib/openid/connect/core/endpoints/pre_configured.py
  oauthlib/openid/connect/core/endpoints/userinfo.py
  oauthlib/openid/connect/core/request_validator.py
  tests/openid/connect/core/endpoints/test_userinfo_endpoint.py
Labels: Feature, OIDC

#673 Add hooks to highlight the possibilities of the framework
  docs/oauth2/oauth2provider-server.dot
Labels: Documentation, OAuth2-Provider

#689 Release 3.1.0
  CHANGELOG.rst
  docs/conf.py
  oauthlib/__init__.py
  tox.ini
Labels: Documentation

#693 Add logo to RTD docs & upgraded tox -e readme build to twine.
  README.rst
  docs/conf.py
  docs/logo/oauth-logo-192x192.png
  docs/logo/oauthlib-banner-700x192.png
  docs/logo/oauthlib-banner.xcf
  docs/logo/oauthlib-logo-128x128.png
  docs/logo/oauthlib-logo-192x192.png
  docs/logo/oauthlib-logo-256x256.png
  docs/logo/oauthlib-logo-32x32.png
  docs/logo/oauthlib-logo-64x64.png
  docs/logo/oauthlib-logo.png
  docs/logo/python-logo-192x192.png
  setup.py
  tox.ini
Labels: Documentation

#697 Fix tests for OAuth1 signature basestring generation,
  oauthlib/oauth1/rfc5849/signature.py
  tests/oauth1/rfc5849/test_signatures.py
Labels: Cleanup, OAuth1

#699 Drop Python 3.4 support
  .travis.yml
  README.rst
  docs/contributing.rst
  setup.py
  tox.ini
Labels: Breaking, Cleanup

#694 Extended the requirements of the authenticate_client method docu…
  oauthlib/oauth2/rfc6749/request_validator.py
Labels: Documentation
